### ISSUE TITLE
Incorrect TC Messages when referencing NUnit 2

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [nunit/teamcity-event-listener#28]
NUnit.Console installed though NuGet

```
NuGet.exe install NUnit.Console  -Version 3.5.0 -OutputDirectory  somedir
```

My example test project references NUnit 2.6.4 and has two test assemblies. The teamcity messages are outputting incorrectly, causing TeamCity to misinterpret them and display the wrong number of tests. 

Example [project link](https://github.com/chris-smith-zocdoc/NunitTestExample)

Example output

```
nunit3-console.exe TestProjectOne.dll TestProjectTwo.dll --workers=1 --teamcity
```

Notice that all the flowId='1' despite there being two dlls
There is also one testSuiteStarted message instead of two

```
NUnit Console Runner 3.5.0 
Copyright (C) 2016 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.14393.0
  CLR Version: 4.0.30319.42000

Test Files
    TestProjectOne.dll
    TestProjectTwo.dll

##teamcity[testSuiteStarted name='TestProjectOne.dll' flowId='1']
##teamcity[testStarted name='TestProjectOne.Class1.MyTestCase(10)' captureStandardOutput='false' flowId='1']
##teamcity[testStarted name='TestProjectTwo.Class1.AnotherTestCase(20)' captureStandardOutput='false' flowId='1']
##teamcity[testFinished name='TestProjectOne.Class1.MyTestCase(10)' duration='21' flowId='1']
##teamcity[testStarted name='TestProjectOne.Class1.MyTestCase(100)' captureStandardOutput='false' flowId='1']
##teamcity[testStarted name='TestProjectTwo.Class1.AnotherTestCase(20)' captureStandardOutput='false' flowId='1']
##teamcity[testFinished name='TestProjectTwo.Class1.AnotherTestCase(20)' duration='31' flowId='1']
##teamcity[testStarted name='TestProjectTwo.Class1.AnotherTestCase(200)' captureStandardOutput='false' flowId='1']
##teamcity[testFinished name='TestProjectOne.Class1.MyTestCase(100)' duration='101' flowId='1']
##teamcity[testStarted name='TestProjectOne.Class1.MyTestCase(1000)' captureStandardOutput='false' flowId='1']
##teamcity[testStarted name='TestProjectTwo.Class1.AnotherTestCase(200)' captureStandardOutput='false' flowId='1']
##teamcity[testFinished name='TestProjectTwo.Class1.AnotherTestCase(200)' duration='200' flowId='1']
##teamcity[testStarted name='TestProjectTwo.Class1.AnotherTestCase(2000)' captureStandardOutput='false' flowId='1']
##teamcity[testFinished name='TestProjectOne.Class1.MyTestCase(1000)' duration='1000' flowId='1']
##teamcity[testStarted name='TestProjectOne.Class2.MyTestCase(10)' captureStandardOutput='false' flowId='1']
##teamcity[testFinished name='TestProjectOne.Class2.MyTestCase(10)' duration='10' flowId='1']
##teamcity[testStarted name='TestProjectOne.Class2.MyTestCase(100)' captureStandardOutput='false' flowId='1']
##teamcity[testFinished name='TestProjectOne.Class2.MyTestCase(100)' duration='101' flowId='1']
##teamcity[testStarted name='TestProjectOne.Class2.MyTestCase(1000)' captureStandardOutput='false' flowId='1']
##teamcity[testStarted name='TestProjectTwo.Class1.AnotherTestCase(2000)' captureStandardOutput='false' flowId='1']
##teamcity[testFinished name='TestProjectTwo.Class1.AnotherTestCase(2000)' duration='2000' flowId='1']
##teamcity[testStarted name='TestProjectTwo.Class2.AnotherTestCase(20)' captureStandardOutput='false' flowId='1']
##teamcity[testFinished name='TestProjectOne.Class2.MyTestCase(1000)' duration='1000' flowId='1']
##teamcity[testFinished name='TestProjectTwo.Class2.AnotherTestCase(20)' duration='20' flowId='1']
##teamcity[testStarted name='TestProjectTwo.Class2.AnotherTestCase(200)' captureStandardOutput='false' flowId='1']
##teamcity[testFinished name='TestProjectTwo.Class2.AnotherTestCase(200)' duration='201' flowId='1']
##teamcity[testStarted name='TestProjectTwo.Class2.AnotherTestCase(2000)' captureStandardOutput='false' flowId='1']
##teamcity[testFinished name='TestProjectTwo.Class2.AnotherTestCase(2000)' duration='2000' flowId='1']
##teamcity[testSuiteFinished name='TestProjectTwo.dll' flowId='1']

Test Run Summary
  Overall result: Passed
  Test Count: 12, Passed: 12, Failed: 0, Inconclusive: 0, Skipped: 0
  Start time: 2016-10-18 17:23:34Z
    End time: 2016-10-18 17:23:38Z
    Duration: 4.522 seconds

Results (nunit3) saved as TestResult.xml

```

Output if I reference NUnit 3.5 instead 

```
NUnit Console Runner 3.5.0 
Copyright (C) 2016 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.14393.0
  CLR Version: 4.0.30319.42000

Test Files
    C:\src\NUnitTestExample\TestProjectOne\TestProjectOne\bin\Debug\TestProjectOne.dll
    C:\src\NUnitTestExample\TestProjectOne\TestProjectTwo\bin\Debug\TestProjectTwo.dll

##teamcity[testSuiteStarted name='TestProjectOne.dll' flowId='1-1010']
##teamcity[testSuiteStarted name='TestProjectTwo.dll' flowId='2-1010']
##teamcity[flowStarted flowId='2-1001' parent='2-1010']
##teamcity[testStarted name='TestProjectTwo.Class1.AnotherTestCase(20)' captureStandardOutput='false' flowId='2-1001']
##teamcity[flowStarted flowId='1-1001' parent='1-1010']
##teamcity[testStarted name='TestProjectOne.Class1.MyTestCase(10)' captureStandardOutput='false' flowId='1-1001']
##teamcity[testFinished name='TestProjectOne.Class1.MyTestCase(10)' duration='15' flowId='1-1001']
##teamcity[flowFinished flowId='1-1001']
##teamcity[flowStarted flowId='1-1002' parent='1-1010']
##teamcity[testStarted name='TestProjectOne.Class1.MyTestCase(100)' captureStandardOutput='false' flowId='1-1002']
##teamcity[testFinished name='TestProjectTwo.Class1.AnotherTestCase(20)' duration='25' flowId='2-1001']
##teamcity[flowFinished flowId='2-1001']
##teamcity[flowStarted flowId='2-1002' parent='2-1010']
##teamcity[testStarted name='TestProjectTwo.Class1.AnotherTestCase(200)' captureStandardOutput='false' flowId='2-1002']
##teamcity[testFinished name='TestProjectOne.Class1.MyTestCase(100)' duration='101' flowId='1-1002']
##teamcity[flowFinished flowId='1-1002']
##teamcity[flowStarted flowId='1-1003' parent='1-1010']
##teamcity[testStarted name='TestProjectOne.Class1.MyTestCase(1000)' captureStandardOutput='false' flowId='1-1003']
##teamcity[testFinished name='TestProjectTwo.Class1.AnotherTestCase(200)' duration='201' flowId='2-1002']
##teamcity[flowFinished flowId='2-1002']
##teamcity[flowStarted flowId='2-1003' parent='2-1010']
##teamcity[testStarted name='TestProjectTwo.Class1.AnotherTestCase(2000)' captureStandardOutput='false' flowId='2-1003']
##teamcity[testFinished name='TestProjectOne.Class1.MyTestCase(1000)' duration='1000' flowId='1-1003']
##teamcity[flowFinished flowId='1-1003']
##teamcity[flowStarted flowId='1-1006' parent='1-1010']
##teamcity[testStarted name='TestProjectOne.Class2.MyTestCase(10)' captureStandardOutput='false' flowId='1-1006']
##teamcity[testFinished name='TestProjectOne.Class2.MyTestCase(10)' duration='11' flowId='1-1006']
##teamcity[flowFinished flowId='1-1006']
##teamcity[flowStarted flowId='1-1007' parent='1-1010']
##teamcity[testStarted name='TestProjectOne.Class2.MyTestCase(100)' captureStandardOutput='false' flowId='1-1007']
##teamcity[testFinished name='TestProjectOne.Class2.MyTestCase(100)' duration='101' flowId='1-1007']
##teamcity[flowFinished flowId='1-1007']
##teamcity[flowStarted flowId='1-1008' parent='1-1010']
##teamcity[testStarted name='TestProjectOne.Class2.MyTestCase(1000)' captureStandardOutput='false' flowId='1-1008']
##teamcity[testFinished name='TestProjectTwo.Class1.AnotherTestCase(2000)' duration='2001' flowId='2-1003']
##teamcity[flowFinished flowId='2-1003']
##teamcity[flowStarted flowId='2-1006' parent='2-1010']
##teamcity[testStarted name='TestProjectTwo.Class2.AnotherTestCase(20)' captureStandardOutput='false' flowId='2-1006']
##teamcity[testFinished name='TestProjectOne.Class2.MyTestCase(1000)' duration='1000' flowId='1-1008']
##teamcity[flowFinished flowId='1-1008']
##teamcity[testFinished name='TestProjectTwo.Class2.AnotherTestCase(20)' duration='21' flowId='2-1006']
##teamcity[flowFinished flowId='2-1006']
##teamcity[testSuiteFinished name='TestProjectOne.dll' flowId='1-1010']
##teamcity[flowStarted flowId='2-1007' parent='2-1010']
##teamcity[testStarted name='TestProjectTwo.Class2.AnotherTestCase(200)' captureStandardOutput='false' flowId='2-1007']
##teamcity[testFinished name='TestProjectTwo.Class2.AnotherTestCase(200)' duration='200' flowId='2-1007']
##teamcity[flowFinished flowId='2-1007']
##teamcity[flowStarted flowId='2-1008' parent='2-1010']
##teamcity[testStarted name='TestProjectTwo.Class2.AnotherTestCase(2000)' captureStandardOutput='false' flowId='2-1008']
##teamcity[testFinished name='TestProjectTwo.Class2.AnotherTestCase(2000)' duration='2000' flowId='2-1008']
##teamcity[flowFinished flowId='2-1008']
##teamcity[testSuiteFinished name='TestProjectTwo.dll' flowId='2-1010']

Run Settings
    DisposeRunners: True
    WorkDirectory: foo\NUnit.ConsoleRunner.3.5.0\tools
    NumberOfTestWorkers: 1
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.0
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False

Test Run Summary
  Overall result: Passed
  Test Count: 12, Passed: 12, Failed: 0, Inconclusive: 0, Skipped: 0
  Start time: 2016-10-18 17:26:19Z
    End time: 2016-10-18 17:26:23Z
    Duration: 4.583 seconds
```

TeamCity (10.0.2) incorrectly shows 11 tests passing instead of 12 when referencing NUnit 2.6. The tests also appear in the wrong scope. MyTestCase belongs to TestProjectOne.dll, not TestProjectTwo.dll

![image](https://cloud.githubusercontent.com/assets/2537809/19490418/1aa4593c-953d-11e6-8208-a2745b54b16d.png)

**Comment by NikolayPianikov** [comment]
@chris-smith-zocdoc it looks like an issue https://github.com/nunit/teamcity-event-listener/issues/14
And it was fixed in 1.0.2. Please ensure that you are using this version. If you are using NuGet packages ensure that `packages` directory does not contain any other NUnit.Extension.TeamCityEventListener.xxx except 1.0.2

The output have to be like the following:
`D:\Downloads\NunitTestExample-master\TestProjectOne>"C:\Projects\GitHub\nunit-teamcity-event-listener\bin\nunit\NUnit.ConsoleRunner.3.5.0-dev-03276\tools\nunit3-console.exe" D:\Downloads\NunitTestExample-master\TestProjectOne\TestProjectOne\bin\Debug\TestProjectOne.dll D:\Downloads\NunitTestExample-master\TestProjectOne\TestProjectTwo\bin\Debug\TestProjectTwo.dll --teamcity 
NUnit Console Runner 3.5.0 
Copyright (C) 2016 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.14393.0
  CLR Version: 4.0.30319.42000

Test Files
    D:\Downloads\NunitTestExample-master\TestProjectOne\TestProjectOne\bin\Debug\TestProjectOne.dll
    D:\Downloads\NunitTestExample-master\TestProjectOne\TestProjectTwo\bin\Debug\TestProjectTwo.dll

##teamcity[testSuiteStarted name='TestProjectOne.dll' flowId='1']
##teamcity[testSuiteStarted name='TestProjectTwo.dll' flowId='2']
##teamcity[testStarted name='TestProjectOne.Class1.MyTestCase(10)' captureStandardOutput='false' flowId='1']
##teamcity[testStarted name='TestProjectTwo.Class1.AnotherTestCase(20)' captureStandardOutput='false' flowId='2']
##teamcity[testFinished name='TestProjectOne.Class1.MyTestCase(10)' duration='16' flowId='1']
##teamcity[testStarted name='TestProjectOne.Class1.MyTestCase(100)' captureStandardOutput='false' flowId='1']
##teamcity[testFinished name='TestProjectTwo.Class1.AnotherTestCase(20)' duration='27' flowId='2']
##teamcity[testStarted name='TestProjectTwo.Class1.AnotherTestCase(200)' captureStandardOutput='false' flowId='2']
##teamcity[testFinished name='TestProjectOne.Class1.MyTestCase(100)' duration='100' flowId='1']
##teamcity[testStarted name='TestProjectOne.Class1.MyTestCase(1000)' captureStandardOutput='false' flowId='1']
##teamcity[testFinished name='TestProjectTwo.Class1.AnotherTestCase(200)' duration='201' flowId='2']
##teamcity[testStarted name='TestProjectTwo.Class1.AnotherTestCase(2000)' captureStandardOutput='false' flowId='2']
##teamcity[testFinished name='TestProjectOne.Class1.MyTestCase(1000)' duration='1001' flowId='1']
##teamcity[testStarted name='TestProjectOne.Class2.MyTestCase(10)' captureStandardOutput='false' flowId='1']
##teamcity[testFinished name='TestProjectOne.Class2.MyTestCase(10)' duration='10' flowId='1']
##teamcity[testStarted name='TestProjectOne.Class2.MyTestCase(100)' captureStandardOutput='false' flowId='1']
##teamcity[testFinished name='TestProjectOne.Class2.MyTestCase(100)' duration='100' flowId='1']
##teamcity[testStarted name='TestProjectOne.Class2.MyTestCase(1000)' captureStandardOutput='false' flowId='1']
##teamcity[testFinished name='TestProjectTwo.Class1.AnotherTestCase(2000)' duration='2001' flowId='2']
##teamcity[testStarted name='TestProjectTwo.Class2.AnotherTestCase(20)' captureStandardOutput='false' flowId='2']
##teamcity[testFinished name='TestProjectOne.Class2.MyTestCase(1000)' duration='1001' flowId='1']
##teamcity[testSuiteFinished name='TestProjectOne.dll' flowId='1']
##teamcity[testFinished name='TestProjectTwo.Class2.AnotherTestCase(20)' duration='21' flowId='2']
##teamcity[testStarted name='TestProjectTwo.Class2.AnotherTestCase(200)' captureStandardOutput='false' flowId='2']
##teamcity[testFinished name='TestProjectTwo.Class2.AnotherTestCase(200)' duration='200' flowId='2']
##teamcity[testStarted name='TestProjectTwo.Class2.AnotherTestCase(2000)' captureStandardOutput='false' flowId='2']
##teamcity[testFinished name='TestProjectTwo.Class2.AnotherTestCase(2000)' duration='2000' flowId='2']
##teamcity[testSuiteFinished name='TestProjectTwo.dll' flowId='2']

Test Run Summary
  Overall result: Passed
  Test Count: 12, Passed: 12, Failed: 0, Inconclusive: 0, Skipped: 0
  Start time: 2016-10-19 14:26:53Z
    End time: 2016-10-19 14:26:57Z
    Duration: 4.503 seconds

Results (nunit3) saved as TestResult.xml
`

**Comment by chris-smith-zocdoc** [comment]
@NikolayPianikov I believe I am using 1.0.2 yet am still having this issue. 

I attached a debugger to nunit3-console and can see the correct version of the assembly being loaded

![image](https://cloud.githubusercontent.com/assets/2537809/19524468/de4b8b9a-95eb-11e6-905f-7f13f09cc31c.png)

This is the folder hierarchy after the nuget install 

```
    Directory: C:\src\NUnitFromNuget


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/18/2016  11:14 AM                NUnit.3.5.0
d-----       10/18/2016  11:18 AM                NUnit.Console.3.5.0
d-----       10/18/2016  11:18 AM                NUnit.ConsoleRunner.3.5.0
d-----       10/18/2016  11:18 AM                NUnit.Extension.NUnitProjectLoader.3.5.0
d-----       10/18/2016  11:18 AM                NUnit.Extension.NUnitV2Driver.3.5.0
d-----       10/18/2016  11:18 AM                NUnit.Extension.NUnitV2ResultWriter.3.5.0
d-----       10/18/2016  11:18 AM                NUnit.Extension.TeamCityEventListener.1.0.2
d-----       10/18/2016  11:18 AM                NUnit.Extension.VSProjectLoader.3.5.0
```

**Comment by NikolayPianikov** [comment]
@chris-smith-zocdoc  I've reproduced it. Thank you. 
@CharliePoole Looks like my PR https://github.com/nunit/nunit-console/pull/38 is not in the code by the some reason. And MyGet feed contains old package NUnit.Extension.NUnitV2Driver.3.5.0-dev-03211 where this issue was fixed, but NuGet NUnit.Extension.NUnitV2Driver.3.5.0 package does not contain this fix.

**Comment by NikolayPianikov** [comment]
I've created the issue https://github.com/nunit/nunit-v2-framework-driver/issues/5. I am closing this issue because fixes are not needed in this extension. I am going make a fix in the https://github.com/nunit/nunit-v2-framework-driver/ repo

**Comment by NikolayPianikov** [comment]
This is hot fix: [nunit.v2.driver.dll.zip](https://github.com/nunit/teamcity-event-listener/files/541487/nunit.v2.driver.dll.zip)

**Comment by CharliePoole** [comment]
@NikolayPianikov You closed this and sent a link to a "hot fix" for one of the NUnit extensions. I'm not sure what we are supposed to do with it. Does it relate to nunit/nunit-v2-framework-driver#5?

**Comment by NikolayPianikov** [comment]
@CharliePoole Yes it relates to https://github.com/nunit/nunit-v2-framework-driver/issues/5
